#!/bin/sh
if [ -n "$TMUX" ]; then
  export TERM=screen-256color
fi

. "$HOME/.cargo/env"

export PAGER='less -F'
export EDITOR=vi

export BAT_PAGER="$PAGER"
export BAT_THEME=GitHub

export XDG_DATA_DIRS="/home/linuxbrew/.linuxbrew/share:$XDG_DATA_DIRS"

export GPG_TTY=$(tty)

MOLD_PATH=$(which mold)
if [ -e $MOLD_PATH ]; then
  export LD=$MOLD_PATH
fi
