#!/bin/sh
if [ -n "$TMUX" ]; then
  export TERM=screen-256color
fi

# Rust
if [ -e "$HOME/.cargo/env" ]; then
    # shellcheck source=/dev/null
    . "$HOME/.cargo/env"
fi

export CARGO_TARGET_DIR="$HOME/.cargo-target"

export PAGER='less -F'
export EDITOR=nvim

export BAT_PAGER="$PAGER"
# export BAT_THEME="Catpuccin Mocha"

export XDG_DATA_DIRS="/home/linuxbrew/.linuxbrew/share:$XDG_DATA_DIRS"

GPG_TTY="$(tty)"
export GPG_TTY

MOLD_PATH=$(which mold)
if [ -e "$MOLD_PATH" ]; then
  export LD="$MOLD_PATH"
fi

export HOMEBREW_NO_ENV_HINTS="true"

if [ ! -n "$SSH_AUTH_SOCK" ]; then
    if [ "$(uname)" = "Darwin" ]; then
        export SSH_AUTH_SOCK="$HOME/Library/Group Containers/2BUA8C4S2C.com.1password/t/agent.sock"
    else
        export SSH_AUTH_SOCK="$HOME/.1password/agent.sock"
    fi
fi

if [ "$GHOSTTY_BIN_DIR" = "$HOME/bin" ]; then
    # so my source build of ghostty can find themes and things
    export GHOSTTY_RESOURCES_DIR="$HOME/bin/share/ghostty"
    export TERMINFO=/home/ray/bin/share/terminfo
fi
