theme = "catppuccin_latte"

[editor]
line-number = "relative"
default-line-ending = "lf"
popup-border = "menu"
color-modes = true
true-color = true
clipboard-provider = "x-clip"

[editor.statusline]
center = ["version-control", "file-type"]

[editor.lsp]
display-inlay-hints = true

[editor.inline-diagnostics]
cursor-line = "hint"
other-lines = "hint"

[editor.indent-guides]
render = true

[editor.file-picker]
hidden = false

[keys.normal]
# like (neo)vim
G = "goto_file_end"

[keys.normal.space]
e = [
  ":sh rm -f /tmp/unique-file-h21a434",
  ":insert-output yazi '%{buffer_name}' --chooser-file=/tmp/unique-file-h21a434",
  ":insert-output echo \"x1b[?1049h\" > /dev/tty",
  ":open %sh{cat /tmp/unique-file-h21a434}",
  ":redraw",
  ":set mouse false",
  ":set mouse true"
]
E = [
  ":sh rm -f /tmp/unique-file-u41ae14",
  ":insert-output yazi '%{workspace_directory}' --chooser-file=/tmp/unique-file-u41ae14",
  ":insert-output echo \"x1b[?1049h\" > /dev/tty",
  ":open %sh{cat /tmp/unique-file-u41ae14}",
  ":redraw",
  ":set mouse false",
  ":set mouse true"
]
