theme = "catppuccin_mocha"

[editor]
line-number = "relative"
default-line-ending = "lf"
popup-border = "menu"
color-modes = true
true-color = true
text-width = 80
#clipboard-provider = "x-clip"

[editor.statusline]
center = ["version-control", "file-type"]

[editor.lsp]
display-inlay-hints = true

[editor.inline-diagnostics]
cursor-line = "hint"
other-lines = "hint"

[editor.indent-guides]
render = true

[editor.file-picker]
#hidden = false

[editor.cursor-shape]
insert = "bar"
select = "underline"

[keys.normal]
C-y = [
    ':sh rm -f /tmp/yazi-unique-file',
    ':insert-output yazi %{buffer_name} --chooser-file=/tmp/yazi-unique-file',
    ':insert-output echo "\x1b[?1049h\x1b[?2004h" > /dev/tty',
    ':open %sh{cat /tmp/yazi-unique-file}',
    ':redraw',
]

[keys.normal.t]
r = ":sh mvn test -Dtest=%{buffer_name}"
