[[language]]
name = "java"
language-servers = ["jdtls"]

[language-server.jdtls]
command = "jdtls"
args = [
    "--add-modules=ALL-SYSTEM",
    "--add-opens",
    "java.base/java.util=ALL-UNNAMED",
    "--add-opens",
    "java.base/java.lang=ALL-UNNAMED",
]

[[language]]
name = "markdown"
language-servers = ["marksman", "mpls"]

[language-server.marksman]
formatter = { command = "dprint", args = ["fmt", "--stdin", "md"] }
auto-format = true

[language-server.mpls]
command = "mpls"
args = ["--enable-emoji", "--no-auto", "--enable-wikilinks"]

[language-server.rust-analyzer.config.check]
command = "clippy"

[language-server.rust-analyzer.config.cargo]
features = "all"
