[user]
name = "Ray Suliteanu"
email = "raysuliteanu@pm.me"

[ui]
default-command = "log"
diff-editor = ["nvim", "-c", "DiffEditor $left $right $output"]
diff-formatter = ":git"
pager = "delta"

[git]
auto-local-bookmark = true

[aliases]
init = ["git", "init"]
