[user]
name = "Ray Suliteanu"
email = "raysuliteanu@pm.me"
signing-key = "~/.ssh/id_rsa"

[ui]
default-command = "log"
diff-editor = ["nvim", "-c", "DiffEditor $left $right $output"]
diff-formatter = ":git"
pager = "delta"
show-cryptographic-signatures = true

[aliases]
init = ["git", "init"]

[remotes.origin]
auto-track-bookmarks = "glob:*"

[signing]
backend = "ssh"
behavior = "own"

[signing.backends.ssh]
allowed-signers = "~/.ssh/allowed_signers"

[template-aliases]
'format_short_cryptographic_signature(sig)' = '''
if(sig,
  "\nSigned-By: " ++ sig.display(),
  ""
)
'''
